# Generated by Django 3.1.4 on 2021-01-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='name')),
                ('Text', models.TextField(blank=True, max_length=500, verbose_name='Desc')),
            ],
        ),
    ]
