# Generated by Django 3.1.4 on 2021-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('headshot', models.ImageField(blank=True, upload_to='img')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Desc')),
            ],
        ),
    ]
